name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run packaging script
        run: tools\package.ps1
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: Packetmock
          path: |
            dist/release.zip
          if-no-files-found: error
